# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1390791536);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1390791656);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1390791296);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1390791416);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131206152524");
user_pref("browser.slowStartup.averageTime", 32240);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20131206152524");
user_pref("browser.startup.homepage_override.mstone", "26.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1390877575615");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1390791175615");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2806);
user_pref("datareporting.sessions.current.main", 30);
user_pref("datareporting.sessions.current.sessionRestored", 1592);
user_pref("datareporting.sessions.current.startTime", "1390791675473");
user_pref("datareporting.sessions.current.totalTime", 10);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1390791115555,\"a\":81,\"t\":556,\"c\":true,\"m\":59401,\"fp\":61798,\"sr\":62929}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"firebug@software.joehewitt.com\":{\"version\":\"1.12.6\",\"type\":\"extension\",\"descriptor\":\"/home/joe/workspace/fileserver/firefox_profile/extensions/firebug@software.joehewitt.com.xpi\"},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"26.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"26.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:26.0");
user_pref("extensions.firebug.allPagesActivation", "on");
user_pref("extensions.firebug.console.enableSites", true);
user_pref("extensions.firebug.cookies.enableSites", true);
user_pref("extensions.firebug.currentVersion", "1.12.6");
user_pref("extensions.firebug.net.enableSites", true);
user_pref("extensions.firebug.script.enableSites", true);
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1390082527000,\"rdfTime\":1375741724000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1386346304000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1386346305000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1390082245000,\"rdfTime\":1386345354000}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"/home/joe/workspace/fileserver/firefox_profile/extensions/firebug@software.joehewitt.com.xpi\",\"mtime\":1390791194000}}}]");
user_pref("extensions.lastAppVersion", "26.0");
user_pref("extensions.lastPlatformVersion", "26.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20131206152524");
user_pref("gecko.mstone", "26.0");
user_pref("general.warnOnAboutConfig", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 101993);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1390791675);
user_pref("toolkit.telemetry.previousBuildID", "20131206152524");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1393383179);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
